name: Build and deply
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: lollo03/tts-vue2
          TARGET_BRANCH: gh_pages
          BUILD_SCRIPT: npm install && npm run build
          BUILD_DIR: dist/
